### ISSUE TITLE
elisp_manual() needs to accept additional inputs

### ISSUE THREAD

**Issue by gutron** [phst/rules_elisp#570]
As an example, magit/ghub's doc is an .org file which tries to pull in an org setup file: https://github.com/magit/ghub/blob/main/docs/ghub.org?plain=1#L12

There's no way right now to pass that setup file (`.orgconfig`) to elisp_manual to generate the texinfo.

**Comment by phst** [comment]
OK, I guess we want something like `additional_inputs`, similar to `additional_compiler_inputs` for `cc_library` etc.

**Comment by gutron** [comment]
The latest commit (9b31929) works and generates the texi docs correctly.  Thanks!
